### ISSUE TITLE
G18a - missing required hours

### ISSUE THREAD

**Issue by andreabr-dixie** [dsu-effectiveness/utValidateR#73]
How far do we want to go back? Do we really want Julie to back fill this data for more than 5 years ago? This is also G13a.

**Comment by jpfeifer-dsu** [comment]
You're the one who suggested 5 years.  I can change this if you want.  Just need to know how far back we want to validate.

**Comment by jpfeifer-dsu** [comment]
The graduation dashboard goes back 10 years.
